main: water.of.cup.chessboards.ChessBoards
name: ChessBoards
version: '1.1.6'
description: Adds chess boards to Minecraft.
author: Nicholas Kopiwoda
api-version: 1.14
softdepends: [Vault]
commands:
  chessboards:
    description: All commands for the ChessBoards plugin.
    aliases: [cb]