main: water.of.cup.chessboards.ChessBoards
name: ChessBoards
version: '0.1'
description: Adds chess boards to Minecraft.
author: Nicholas Kopiwoda
api-version: 1.14
commands:
  chessboards:
    description: All commands for the ChessBoards plugin.
    aliases: [cb]